#!/usr/bin/env python

from AutoADAG import *
import ConfigParser
from Pegasus.DAX3 import *
import getpass
import logging
import math
import optparse
import os
import re
import socket
import string
import subprocess
import sys
import time



# to setup python lib dir for importing Pegasus PYTHON DAX API
pegasus_config = os.path.join("pegasus-config") + " --noeoln --python"
lib_dir = subprocess.Popen(pegasus_config,
                           stdout=subprocess.PIPE,
                           shell=True).communicate()[0]
#Insert this directory in our search path
os.sys.path.insert(0, lib_dir)


# --- global variables ----------------------------------------------------------------

logger      = logging.getLogger("my_logger")
conf        = None
debug       = False
added_execs = []


# --- classes -------------------------------------------------------------------------

class ComputeJob(Job):
    """ A Pegasus DAX Job with extra information such as cpu and memory
    requirements, for both single and peagaus-mpi-cluster execution
    """

    def __init__(self, name, cores=1, mem_gb=2, partition="part1"):
        Job.__init__(self, name=name)
        
        # label based clustering
        self.addProfile(Profile(Namespace.PEGASUS, 
                                key="label",
                                value=partition))
  
        # standard resource requirements for all jobs
        mem_mb = mem_gb * 1000
        self.addProfile(Profile(Namespace.CONDOR,
                                key="request_cpus",
                                value=str(cores)))
        self.addProfile(Profile(Namespace.PEGASUS,
                                key="pmc_request_cpus",
                                value=str(cores)))
        self.addProfile(Profile(Namespace.CONDOR,
                                key="request_memory",
                                value=str(mem_mb)))
        self.addProfile(Profile(Namespace.PEGASUS,
                                key="pmc_request_memory",
                                value=str(mem_mb)))
        self.addProfile(Profile(Namespace.CONDOR,
                                key="request_disk",
                                value=str(20*1024*1024)))

        # special sauce for TACC - we want smaller jobs to go to the normal
        # compute nodes and the large memory ones to go to the large memory
        # nodes
        if re.search('stampede', conf.get("local", "exec_env")):
            hosts = conf.get("exec_environment", "hosts_" + partition)
            cores = str(16 * int(hosts))
            self.addProfile(Profile(Namespace.GLOBUS,
                                    key="queue",
                                    value="normal"))
            self.addProfile(Profile(Namespace.GLOBUS,
                                    key="hostcount",
                                    value=hosts))
            self.addProfile(Profile(Namespace.GLOBUS,
                                    key="count",
                                    value=cores))
            self.addProfile(Profile(Namespace.ENV,
                                    key="PMC_HOST_MEMORY",
                                    value="29000"))

        # required for the Pegasus accounting
        self.addProfile(Profile(Namespace.PEGASUS,
                                key="cores",
                                value=str(cores)))
  


# --- functions -----------------------------------------------------------------------


def setup_logger(verbose):
    """ Use a console logger for all output to the user """

    # log to the console
    console = logging.StreamHandler()

    # default log level - make logger/console match
    logger.setLevel(logging.INFO)
    console.setLevel(logging.INFO)

    if verbose:
        logger.setLevel(logging.DEBUG)
        console.setLevel(logging.DEBUG)

    # formatter
    formatter = logging.Formatter("%(asctime)s %(levelname)7s:  %(message)s")
    console.setFormatter(formatter)
    logger.addHandler(console)
    logger.debug("Logger has been configured")


def myexec(cmd_line):
    """ Convenience function as we are shelling out a fair amount """
    
    sys.stdout.flush()
    p = subprocess.Popen(cmd_line + " 2>&1", shell=True)
    stdoutdata, stderrdata = p.communicate()
    r = p.returncode
    if r != 0:
        raise RuntimeError("Command '%s' failed with error code %s" \
                           % (cmd_line, r))


def proxy_check():
    """ Verify that the user has a proxy and it is valid for a long time """
    p = subprocess.Popen("grid-proxy-info -timeleft", shell=True, 
                         stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    stdoutdata, stderrdata = p.communicate()
    r = p.returncode
    if r != 0:
        logger.error(stderrdata)
        raise RuntimeError("Command '%s' failed with error code %s" \
                           % (cmd_line, r))
    timeleft = int(stdoutdata)

    # two weeks minimum lifetime
    if timeleft < (60*60*24*10):
        raise RuntimeError("There is not enough time left on your grid" +
                           " proxy. Please renew, then run this command" +
                           " again")

        
def generate_site_catalog():
    """ Uses a templete file to produce the Pegasus site catalog """
    
    logger.info("Generating sites.catalog")
    inf = open("conf/" + conf.get("local", "exec_env") + 
               "/sites.catalog.template", 'r')
    template = string.Template(inf.read())
    inf.close()

    outf = open(conf.get("local", "work_dir") + "/sites.catalog", "w")
    outf.write(template.substitute(
                        submit_host = socket.gethostname(),
                        username = getpass.getuser(), 
                        home = os.path.expanduser('~'),
                        top_dir = conf.get("local", "top_dir"),
                        work_dir = conf.get("local", "work_dir"),
                        pegasus_bin = conf.get("local", "pegasus_bin"),
                        irods_bin = conf.get("local", "irods_bin"),
                        tacc_allocation = conf.get("tacc", "allocation"),
                        tacc_username = conf.get("tacc", "username"),
                        tacc_storage_group = conf.get("tacc", "storage_group"),
              ))
    outf.close()
   

def read_input_lists(ref_urls, fastq_urls):
    """ The user provides a list of reference file URLs and pairs of fastq 
    URLs to be processed.
    """
    
    # first the reference
    inf = open(conf.get("local", "top_dir") + "/inputs-ref.txt", "r")
    for line in inf.readlines():
        line = line.rstrip('\n')
        if line == "":
            continue
        ref_urls.append(line)
    inf.close()

    inf = open(conf.get("local", "top_dir") + "/inputs-fastq.txt", "r")
    for line in inf.readlines():
        line = line.rstrip('\n')
        if line == "":
            continue
        fastq_urls.append(line)
    inf.close()

    # sanity checks
    if len(fastq_urls) == 0:
        logger.error("Did not find fastq files")
        sys.exit(1)
    if len(fastq_urls) % 2 != 0:
        logger.error("Found an uneven number of fastq files in input list")
        sys.exit(1)


def extract_lfn(url):
    """ determine a logical file name (basename) from a given URL """
    return re.sub(".*/", "", url)


def local_pfn(path):
    """ generates a full pfn given a local path """
    pfn = "scp://" + getpass.getuser() + "@" + socket.gethostname() + "/" + path
    return pfn
  

def extract_fasta_basefile(file_list):
    """ find the base fasta file given a list of reference files """
    for f in file_list:
        if re.search("(.fa|.fasta|.con)$", f.name):
            return f


def extract_read_id(url):
    """ read id is the base name (for example:
    HN001_FCD1P1JACXX_L6_SZAIPI024836-36 from
    HN001_FCD1P1JACXX_L6_SZAIPI024836-36_1.fq)
    """
    name = re.sub(".*/", "", url)
    name = re.sub("_[12]\..*", "", name)
    return name


def extract_sample_id(url):
    """ sample name is the first part of the base name (for example:
    IRIS_313-10020 from
    IRIS_313-10020_111221_I596_FCD0HFCACXX_L6_RICwdsRSYHSD23-3-IPAAPEK-62_1.fq.gz
    HN001 from
    HN001_FCD1P1JACXX_L6_SZAIPI024836-36_1.fq)
    """
    r = parse_filename(url)
    return r['sample_name']


def parse_filename(url):
    """ parses an URL and extracts:
    In "AB03_111221_I596_FCD0HFCACXX_L4_RICwdsRSYHSD23-2-IPAAPEK-57_1.fq.gz"

    AB03 is the sample name (SM).
    I think that 111221_I596 encodes run/machine info.
    FCD0HFCACXX -- flow cell
    L4 -- lane (FCD0HFCACXX_L4 is RGID)
    RICwdsRSYHSD23-2-IPAAPEK-57  -- library (LB)
    """
    result = {}
    s = extract_read_id(url)
    s = re.sub(".*/", "", s)
    if s.startswith("IRIS_") or s.startswith("IRS_"):
        m = re.match("^(IRI?S_[0-9]+-[0-9]+)_", s)
        if not m:
            raise RuntimeError("Unable to extract sample name from %s" %(url))
        result['sample_name'] = m.group(1)
    else:
        result['sample_name'] = re.sub("_.*", "", s)

    # let's trim sample_name of the string to get an easier regex for the
    # rest of the attributes
    s = s[len(result['sample_name']) + 1:]
   
    # 111220_I631_FCD0LYUACXX_L7_RICwdsRSYHSD14-3-IPAAPEK-142
    m = re.match("^([a-zA-Z0-9]+_[a-zA-Z0-9]+)_([a-zA-Z0-9]+)_(L[0-9])_(.+)$", s)
    if not m:
        raise RuntimeError("Unable to extract sample attributes from %s" %(url))
    result['run_info'] = m.group(1)
    result['flow_cell'] = m.group(2)
    result['lane'] = m.group(3)
    result['library'] = m.group(4)
    # and for convenience...
    result['rgid'] = result['flow_cell'] + "_" + result['lane']
    result['lb'] = result['library']
    return result


def add_executable(dax, logical_name, wrapper_name):
    """ adds executables to the DAX-level replica catalog """
    global added_execs

    if logical_name in added_execs:
        return

    base_url = local_pfn(conf.get("local", "top_dir"))    
    
    wrapper = Executable(name=logical_name, 
                         arch="x86_64",
                         installed=False)
    wrapper.addPFN(PFN(base_url + "/wrappers/" + wrapper_name, "local"))
    dax.addExecutable(wrapper)

    added_execs.append(logical_name)
  

def check_inputs(read_id, dax, software_tar, ref_files, wf_files, software_job, inputs_validated_job):

    add_executable(dax, "check-input-pair", "check-input-pair")
    j = ComputeJob("check-input-pair", cores = 1, mem_gb = 2, partition = "part1")
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files['paired_read1_fastq'], link=Link.INPUT)
    j.uses(wf_files['paired_read2_fastq'], link=Link.INPUT)
    j.addArguments(wf_files['paired_read1_fastq'], wf_files['paired_read2_fastq'])
    dax.addJob(j)
    dax.depends(parent=software_job, child=j)
    dax.depends(parent=j, child=inputs_validated_job)
    
    # next step
    seqtk(read_id,
          dax,
          software_tar,
          ref_files,
          wf_files,
          inputs_validated_job)


def seqtk(read_id, dax, software_tar, ref_files, wf_files, inputs_validated_job):

    add_executable(dax, "seqtk", "seqtk-wrapper")
    j = ComputeJob("seqtk", cores = 1, mem_gb = 2, partition = "part1")
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files['paired_read1_fastq'], link=Link.INPUT)
    j.uses(wf_files['paired_read1_fastq_postseqtk'], link=Link.OUTPUT, transfer=False)
    j.setStdout(wf_files['paired_read1_fastq_postseqtk'])
    j.addArguments("seq", "-VQ64", wf_files['paired_read1_fastq'])
    dax.addJob(j)
    dax.depends(parent=inputs_validated_job, child=j)
    
    add_executable(dax, "seqtk", "seqtk-wrapper")
    j = ComputeJob("seqtk", cores = 1, mem_gb = 2, partition = "part1")
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files['paired_read2_fastq'], link=Link.INPUT)
    j.uses(wf_files['paired_read2_fastq_postseqtk'], link=Link.OUTPUT, transfer=False)
    j.setStdout(wf_files['paired_read2_fastq_postseqtk'])
    j.addArguments("seq", "-VQ64", wf_files['paired_read2_fastq'])
    dax.addJob(j)
    dax.depends(parent=inputs_validated_job, child=j)

    # next step
    alignment_to_reference(read_id,
                           dax,
                           software_tar,
                           ref_files,
                           wf_files)
 

def alignment_to_reference(read_id, dax, software_tar, ref_files, wf_files):
    
    # Note that the cores we give Pegasus and the -t does not match. 
    # Oversubscriptions is ok, as bwa can not keep all the cores busy 100%
    # of the time.
    add_executable(dax, "alignment_to_reference", "bwa-wrapper")
    j = ComputeJob("alignment_to_reference", cores = 7, mem_gb = 8,
                   partition = "part1")

    # build the filter command line argument based on information encoded
    # in the file name
    # -R '@RG\tID:FCC31JLACXX_L4\tSM:USB-213\tPL:illumina\tLB:SZAIPI035559-66'
    # _TAB_ will be substituted with \t in the wrapper
    attr = parse_filename(wf_files['paired_read1_fastq'].name)
    farg = "'@RG_TAB_ID:" + attr['rgid'] + "_TAB_SM:" + attr['sample_name'] + \
           "_TAB_PL:illumina_TAB_LB:" + attr['lb'] + "'"
    
    # determine which is the fasta file
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files['paired_read1_fastq_postseqtk'], link=Link.INPUT)
    j.uses(wf_files['paired_read2_fastq_postseqtk'], link=Link.INPUT)
    j.uses(wf_files['sam'], link=Link.OUTPUT, transfer=debug)
    
    j.setStdout(wf_files['sam'])
    
    j.addArguments("mem",
                   "-t", "12",
                   "-M",
                   "-R", farg,
                   extract_fasta_basefile(ref_files), 
                   wf_files['paired_read1_fastq_postseqtk'],
                   wf_files['paired_read2_fastq_postseqtk'])
    dax.addJob(j)

    # next step    
    sortsam_job = sort_sam(read_id, dax, software_tar, ref_files, wf_files)
    
    return j


def sort_sam(read_id, dax, software_tar, ref_files, wf_files):

    add_executable(dax, "sort_sam", "picard-wrapper")
    j = ComputeJob("sort_sam", cores = 1, mem_gb = 23, 
                   partition = "part1")
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files['sam'], link=Link.INPUT)
    j.uses(wf_files['sorted_reads'], link=Link.OUTPUT, transfer=debug)
    j.uses(wf_files['sorted_index'], link=Link.OUTPUT, transfer=debug)
    
    j.addArguments("SortSam.jar",
                   "CREATE_INDEX=TRUE",
                   "MAX_RECORDS_IN_RAM=5000000",
                   "TMP_DIR=.",
                   "I=" + wf_files['sam'].name,
                   "O=" + wf_files['sorted_reads'].name,
                   "SO=coordinate",
                   "VALIDATION_STRINGENCY=LENIENT")
    dax.addJob(j)


def merge(dax, software_tar, ref_files, wf_files, read_ids):

    sample_reads = {}

    # group the reads per sample
    for r in read_ids:
        sample = extract_sample_id(r)
        if not sample in sample_reads:
            sample_reads[sample] = []
        sample_reads[sample].append(r)
   
    for sample, reads in sample_reads.items():
        
        fname = conf.get("local", "run_id") + "-" + sample

        add_executable(dax, "merge", "samtools-wrapper")
        j = ComputeJob("merge", cores = 1, mem_gb = 5, partition = "part2")
        j.addArguments("merge")
        
        # outputs - only the bam files gets generated here, the index
        # is generated in the next job
        merged_bam = File(fname + ".bam")
        wf_files[fname + ".bam"] =  merged_bam
        j.uses(merged_bam, link=Link.OUTPUT, transfer=debug)
        j.addArguments(merged_bam)
        
        # inputs
        j.uses(software_tar, link=Link.INPUT)
        for r in reads:
            rf = File(conf.get("local", "run_id") + "-" + r + "_sorted_reads.bam")
            ri = File(conf.get("local", "run_id") + "-" + r + "_sorted_reads.bai")
            j.uses(rf, link=Link.INPUT)
            j.uses(ri, link=Link.INPUT)
            j.addArguments(rf)
        dax.addJob(j)
        
        dedup_job = dedup(dax, software_tar, ref_files, wf_files, sample, fname)

    

def dedup(dax, software_tar, ref_files, wf_files, sample_id, base_fname):

    # created files
    wf_files[base_fname + ".deduped.bam"] = File(base_fname + ".deduped.bam")
    wf_files[base_fname + ".deduped.bai"] = File(base_fname + ".deduped.bai")
    wf_files[base_fname + ".deduped.metrics"] = File(base_fname + ".deduped.metrics")

    add_executable(dax, "dedup", "picard-wrapper")
    j = ComputeJob("dedup", cores = 1, mem_gb = 23,
                   partition = "part2")
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files[base_fname + ".bam"], link=Link.INPUT)
    #j.uses(wf_files[base_fname + "_sorted_reads.bai"], link=Link.INPUT)
    j.uses(wf_files[base_fname + ".deduped.bam"], link=Link.OUTPUT, transfer=debug)
    j.uses(wf_files[base_fname + ".deduped.bai"], link=Link.OUTPUT, transfer=debug)
    j.uses(wf_files[base_fname + ".deduped.metrics"], link=Link.OUTPUT, transfer=debug)
    
    j.addArguments("MarkDuplicates.jar",
                   "CREATE_INDEX=TRUE",
                   "MAX_RECORDS_IN_RAM=5000000",
                   "TMP_DIR=.",
                   "I=" + wf_files[base_fname + ".bam"].name,
                   "O=" + wf_files[base_fname + ".deduped.bam"].name,
                   "METRICS_FILE=" + wf_files[base_fname + ".deduped.metrics"].name,
                   "VALIDATION_STRINGENCY=LENIENT")

    dax.addJob(j)

    realign_target_creator(dax, software_tar, ref_files, wf_files, sample_id, base_fname)


def realign_target_creator(dax, software_tar, ref_files, wf_files, sample_id, base_fname):

    # created files
    wf_files[base_fname + "_intervals.list"] = File(base_fname + "_intervals.list")

    add_executable(dax, "realign_target_creator", "gatk-wrapper")
    j = ComputeJob("realign_target_creator", cores = 15, mem_gb = 11,
                   partition = "part2")
    j.uses(software_tar, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files[base_fname + ".deduped.bam"], link=Link.INPUT)
    j.uses(wf_files[base_fname + ".deduped.bai"], link=Link.INPUT)
    j.uses(wf_files[base_fname + "_intervals.list"], link=Link.OUTPUT, transfer=debug)
    
    j.addArguments("-T", "RealignerTargetCreator",
                   "-nt", "15",
                   "-R", extract_fasta_basefile(ref_files),
                   "-I", wf_files[base_fname + ".deduped.bam"],
                   "-o", wf_files[base_fname + "_intervals.list"]) 
    dax.addJob(j)
    
    indel_realign(dax, software_tar, ref_files, wf_files, sample_id, base_fname)
    

def indel_realign(dax, software_tar, ref_files, wf_files, sample_id, base_fname):
    
    # created files
    wf_files[base_fname + "_indel_realigned.bam"] = File(base_fname + "_indel_realigned.bam")
    wf_files[base_fname + "_indel_realigned.bai"] = File(base_fname + "_indel_realigned.bai")

    # IndelRealigner can only be run single threaded
    add_executable(dax, "indel_realign", "gatk-wrapper")   
    j = ComputeJob("indel_realign", cores = 1, mem_gb = 11,
                   partition = "part2")
    j.uses(software_tar, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files[base_fname + ".deduped.bam"], link=Link.INPUT)
    j.uses(wf_files[base_fname + ".deduped.bai"], link=Link.INPUT)
    j.uses(wf_files[base_fname + "_intervals.list"], link=Link.INPUT)
    j.uses(wf_files[base_fname + "_indel_realigned.bam"], link=Link.OUTPUT, transfer=debug)
    j.uses(wf_files[base_fname + "_indel_realigned.bai"], link=Link.OUTPUT, transfer=debug)
    
    j.addArguments("-T", "IndelRealigner",
                   "-R", extract_fasta_basefile(ref_files),
                   "-I", wf_files[base_fname + ".deduped.bam"],
                   "--filter_mismatching_base_and_quals",
                   "--filter_bases_not_stored",
                   "-targetIntervals", wf_files[base_fname + "_intervals.list"],
                   "-o", wf_files[base_fname + "_indel_realigned.bam"])
    dax.addJob(j)

    filter(dax, software_tar, ref_files, wf_files, sample_id, base_fname)


def filter(dax, software_tar, ref_files, wf_files, sample_id, base_fname):

    # filter
    add_executable(dax, "filter", "samtools-filter-wrapper")
    j = ComputeJob("filter", cores = 1, mem_gb = 5, partition = "part2")
    filtered_bam = File(base_fname + ".paired.q20.bam")
    wf_files[filtered_bam.name] = filtered_bam
    j.addArguments(wf_files[base_fname + "_indel_realigned.bam"], filtered_bam)
    j.uses(software_tar, link=Link.INPUT)
    j.uses(wf_files[base_fname + "_indel_realigned.bam"], link=Link.INPUT)
    j.uses(filtered_bam, link=Link.OUTPUT, transfer=True)
    dax.addJob(j)
    
    # we also need to index the filtered bam
    filtered_index = File(base_fname + ".paired.q20.bam.bai")
    wf_files[base_fname + ".paired.q20.bam.bai"] =  filtered_index
    add_executable(dax, "filtered_index", "samtools-wrapper")
    j = ComputeJob("filtered_index", cores = 1, mem_gb = 5, partition = "part2")
    j.addArguments("index")
    j.addArguments(filtered_bam)
    j.uses(software_tar, link=Link.INPUT)
    j.uses(filtered_bam, link=Link.INPUT)
    j.uses(filtered_index, link=Link.OUTPUT, transfer=True)
    dax.addJob(j)

    # and then cram it to get the final output file
    filtered_cram = File(base_fname + ".paired.q20.cram")
    wf_files[filtered_cram.name] = filtered_cram
    add_executable(dax, "cram", "cram-wrapper")
    j = ComputeJob("cram", cores = 1, mem_gb = 3, partition = "part2")
    j.addArguments(filtered_bam, extract_fasta_basefile(ref_files), filtered_cram)
    j.uses(software_tar, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(filtered_bam, link=Link.INPUT)
    j.uses(filtered_index, link=Link.INPUT)
    j.uses(filtered_cram, link=Link.OUTPUT, transfer=debug)
    dax.addJob(j)

    for i in range(1, 13):
        chromosome = "%d" %(i)
        haplotype_caller(dax, software_tar, ref_files,
                         wf_files, sample_id, chromosome)



def haplotype_caller(dax, software_file, ref_files, wf_files,
                     sample_id, chromosome):

    add_executable(dax, "haplotype_caller", "gatk-wrapper")
    j = ComputeJob("haplotype_caller", cores = 1, mem_gb = 5,
                  partition = "part3")
    
    # inputs
    j.uses(software_file, link=Link.INPUT)
    for f in ref_files:
        j.uses(f, link=Link.INPUT)
    j.uses(wf_files[conf.get("local", "run_id") + "-" + sample_id + ".paired.q20.bam"], link=Link.INPUT)
    j.uses(wf_files[conf.get("local", "run_id") + "-" + sample_id + ".paired.q20.bam.bai"], link=Link.INPUT)

    # outputs
    fname = conf.get("local", "run_id") + "-" + sample_id + "_" + chromosome + ".vcf"
    wf_files[fname] = File(fname)
    j.uses(wf_files[fname], link=Link.OUTPUT, transfer=debug)
    wf_files[fname + ".idx"] = File(fname + ".idx")
    j.uses(wf_files[fname + ".idx"], link=Link.OUTPUT, transfer=True)
    
    j.addArguments("-T", "HaplotypeCaller",
                   "--emitRefConfidence", "GVCF",
                   "--variant_index_type", "LINEAR",
                   "--variant_index_parameter", "128000",
                   "-L", chromosome,
                   "-R", extract_fasta_basefile(ref_files),
                   "-I", wf_files[conf.get("local", "run_id") + "-" + sample_id + ".paired.q20.bam"],
                   "-o", wf_files[fname])
    dax.addJob(j)

    # gzip the result to save space
    fgzip = File(fname + ".gz")
    add_executable(dax, "gzip", "gzip-wrapper")
    j = ComputeJob("gzip", cores = 1, mem_gb = 1, partition = "part3")
    j.addArguments(wf_files[fname], fgzip)
    j.uses(wf_files[fname], link=Link.INPUT)
    j.uses(fgzip, link=Link.OUTPUT, transfer=True)
    dax.addJob(j)


def generate_dax():
    """ generates the Pegasus DAX (directed acyclic graph - abstract XML)
    which is a description of a workflow """
    
    logger.info("Generating abstract workflow (DAX)")
    
    dax = AutoADAG("irri")
    
    # The key to adding jobs to this workflow is the AutoADAG - it allows you
    # to add jobs with listed input and output files, and then the AutoADAG
    # will figure out the relationships between the jobs. There is no need
    # to list parent/child relationships, but you can do that if you feel it
    # makes the relationships more clear than just specifying the
    # inputs/outputs.
        
    # email notificiations for when the state of the workflow changes
    dax.invoke('all', conf.get("local", "top_dir") + "/email-notify")
    
    ref_urls = []
    fastq_urls = []
    read_input_lists(ref_urls, fastq_urls)

    # determine how many TACC compute nodes we need
    hosts = max( int(len(fastq_urls) / 40), 1 )
    conf.set("exec_environment", "hosts_part1", str(hosts))
    conf.set("exec_environment", "hosts_part2", str(hosts))
    conf.set("exec_environment", "hosts_part3", str(hosts))

    # we need to bring a copy of the software with us
    software_tar = File("software.tar.gz")
    software_tar.addPFN(PFN(local_pfn(conf.get("local", "work_dir") + "/software.tar.gz"), "local"))
    dax.addFile(software_tar)    
    add_executable(dax, "software-wrapper", "software-wrapper")
    software_job = ComputeJob("software-wrapper", cores=1, mem_gb=1)
    software_job.uses(software_tar, link=Link.INPUT)
    dax.addJob(software_job)
    
    add_executable(dax, "inputs-validated", "inputs-validated")
    inputs_validated_job = ComputeJob("inputs-validated", cores=1, mem_gb=1)
    dax.addJob(inputs_validated_job)

    # we need to track files across jobs
    wf_files = {}
    read_ids = []
    
    # reference genome    
    ref_files = []
    for url in ref_urls:
        f = File(extract_lfn(url))
        f.addPFN(PFN(url, "irods_iplant"))
        dax.addFile(f)
        # put these in a list so jobs can pick them up
        ref_files.append(f)

    for lane in range(len(fastq_urls) / 2):

        # input files for this lane   
        wf_files['paired_read1_fastq'] = File(extract_lfn(fastq_urls[lane * 2]))
        wf_files['paired_read1_fastq'].addPFN(PFN(fastq_urls[lane * 2], "irods_iplant"))
        dax.addFile(wf_files['paired_read1_fastq'])

        wf_files['paired_read2_fastq'] = File(extract_lfn(fastq_urls[lane * 2 + 1]))
        wf_files['paired_read2_fastq'].addPFN(PFN(fastq_urls[lane * 2 + 1], "irods_iplant"))
        dax.addFile(wf_files['paired_read2_fastq'])

        read_id = extract_read_id(wf_files['paired_read1_fastq'].name)

        # files we need to track
        fn = re.sub('\.gz$', '', wf_files['paired_read1_fastq'].name)
        wf_files['paired_read1_fastq_postseqtk'] = File(fn)
        fn = re.sub('\.gz$', '', wf_files['paired_read2_fastq'].name)
        wf_files['paired_read2_fastq_postseqtk'] = File(fn)
        wf_files['sam'] = File(conf.get("local", "run_id") + "-" + read_id + "_aligned_reads.sam")
        wf_files['sorted_reads'] = File(conf.get("local", "run_id") + "-" + read_id + "_sorted_reads.bam")
        wf_files['sorted_index'] = File(conf.get("local", "run_id") + "-" + read_id + "_sorted_reads.bai")
    
        # Step 1 - dependent jobs are now added in the parent jobs
        check_inputs(read_id,
                     dax,
                     software_tar,
                     ref_files,
                     wf_files,
                     software_job,
                     inputs_validated_job)

        # keep a list of samples for the GenotypeGVCFs call
        read_ids.append(read_id)

    # merge all the sorted sams
    merge(dax, software_tar, ref_files, wf_files, read_ids)
 
    # write out the dax
    dax_file = open(conf.get("local", "work_dir") + "/irri.dax", "w")
    dax.writeXML(dax_file)
    dax_file.close()


def main():
    global conf
    global debug
    
    setup_logger(False)

    # Configure command line option parser
    prog_usage = "usage: workflow-generator [options]"
    parser = optparse.OptionParser(usage=prog_usage)

    parser.add_option("-e", "--exec-env", action = "store", dest = "exec_env",
                      help = "Handle for the target execution environment.")
    parser.add_option("-d", "--debug", action = "store_true", dest = "debug",
                      help = "Run the workflow in debug mode. Intermediate products will be staged to output site.")

    # Parse command line options
    (options, args) = parser.parse_args()
    if options.exec_env == None:
        logger.fatal("Please specify an execution environment with --exec-env")
        sys.exit(1)

    debug = options.debug
    if debug is None:
        debug = False

    # read the config file and add those settings to the option object
    conf = ConfigParser.SafeConfigParser({'username': getpass.getuser()})
    r = conf.read([os.environ['HOME'] + "/.irri-workflow.conf", \
                   "conf/%s/site.conf" % options.exec_env])
    if len(r) != 2:
        logger.fatal("Unable to read configuration files for that environment")
        sys.exit(1)

    conf.set("local", "username", getpass.getuser())
    conf.set("local", "exec_env", options.exec_env)
    conf.set("local", "top_dir", os.path.dirname(os.path.realpath( __file__ )))

    # run id
    conf.set("local", "run_id", time.strftime("%Y%m%d-%H%M%S", time.gmtime()))

    # add the run id to the work dir
    conf.set("local", "work_dir", conf.get("local", "work_dir") + "/" + 
                                  conf.get("local", "run_id"))
    
    # local Pegasus environment
    pegasus_config = os.path.join("pegasus-config") + " --noeoln --bin"
    pegasus_bin_dir = subprocess.Popen(pegasus_config,
                                       stdout=subprocess.PIPE,
                                       shell=True).communicate()[0]
    conf.set("local", "pegasus_bin", pegasus_bin_dir)

    # check proxy before doing anything else
    proxy_check()
    
    # create a local work directory for the workflow
    logger.info("Setting up work directory at %s" \
                %(conf.get("local", "work_dir")))
    if os.path.exists(conf.get("local", "work_dir")):
        logger.fatal("Work directory already exists") 
        os.exit(1)
    os.makedirs(conf.get("local", "work_dir"))

    generate_site_catalog()

    # FIXME: what should we copy / keep in the top dir?
    myexec("cp software.tar.gz " + \
            conf.get("local", "work_dir") + "/software.tar.gz")
    myexec("cp conf/" + conf.get("local", "exec_env") + 
           "/transformations.catalog " + 
           conf.get("local", "work_dir") + "/transformations.catalog")
    myexec("cp conf/" + conf.get("local", "exec_env") + 
           "/replica.catalog " + 
           conf.get("local", "work_dir") + "/replica.catalog")

    generate_dax()

    # submit
    logger.info("Planning workflow...")
    os.chdir(conf.get("local", "work_dir"))
    cmd = "pegasus-plan" + \
          " --conf " + conf.get("local", "top_dir") + \
          "/conf/" + conf.get("local", "exec_env") + "/pegasus.conf" + \
          " --dir ." + \
          " --relative-dir wf-" + conf.get("local", "run_id") + \
          " --sites execution"
    
    if conf.get("exec_environment", "output_site") != "":
        cmd += " --output-site " + conf.get("exec_environment", "output_site")
              
    if conf.get("exec_environment", "staging_site") != "":
        cmd += " --staging " + conf.get("exec_environment", "staging_site")
          
    if conf.get("exec_environment", "job_clustering") != "":
        cmd += " --cluster " + conf.get("exec_environment", "job_clustering")
          
    cmd += " --dax irri.dax"
    logger.info(cmd)
    myexec(cmd + " 2>&1 | tee pegasus-plan.out")


if __name__ == "__main__":
    main()

