#!/bin/bash

set -e
version="0.7.12"
if [ ! -d software ]; then
    tar xzf software.tar.gz
fi

if [ "x$TMPDIR_OVERRIDE" != "x" ]; then
   export TMPDIR="$TMPDIR_OVERRIDE"
fi
if [ "x$TMPDIR" = "x" ]; then
   export TMPDIR=/tmp
fi
if [ ! -e "$TMPDIR" ]; then
    mkdir -p $TMPDIR
fi

ARGS=`echo "$@" | sed 's/_TAB_/\\\t/g'`

./software/bwa-$version/bwa $ARGS

