#!/usr/bin/python

# stat the two files in the input pair and verify that the files
# are of non-zero size and with 20% of size of each other

import os
import sys

fname1 = sys.argv[1]
fname2 = sys.argv[2]

size1 = os.path.getsize(fname1)
size2 = os.path.getsize(fname2)

if size1 < 1000:
    raise Exception("File %s is too small: %d bytes" %(fname1, size1)) 

if size2 < 1000:
    raise Exception("File %s is too small: %d bytes" %(fname2, size2)) 

if (size1 < size2 * .8) or (size1 > size2 * 1.2):
    raise Exception("File %s and %s are more than 20% size different" %(fname1, fname2)) 


