#!/usr/bin/python

# stat the two files in the input pair and verify that the files
# are of non-zero size and with 20% of size of each other

import os
import sys
import subprocess

def backticks(cmd_line):
    return subprocess.Popen(cmd_line, shell=True,
                            stdout=subprocess.PIPE).communicate()[0]

fname1 = sys.argv[1]
fname2 = sys.argv[2]

size1 = os.path.getsize(fname1)
size2 = os.path.getsize(fname2)

if size1 < 1000:
    raise Exception("File %s is too small: %d bytes" %(fname1, size1)) 

if size2 < 1000:
    raise Exception("File %s is too small: %d bytes" %(fname2, size2)) 

lines1 = int(backticks("cat %s | gunzip - | egrep '^@' | wc -l" %(fname1)))
lines2 = int(backticks("cat %s | gunzip - | egrep '^@' | wc -l" %(fname2)))

print("%s has %d lines" %(fname1, lines1))
print("%s has %d lines" %(fname2, lines2))
if lines1 != lines2:
    raise Exception("The number of lines differ in the files")


